name: Fetch & Deploy SmartNews Feed

on:
  schedule:
    - cron: "*/30 * * * *"      # every 30 minutes
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write          # REQUIRED for Pages
  id-token: write       # REQUIRED for Pages OIDC

jobs:
  build-and-deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install XML tools (xmllint)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends libxml2-utils

      # ---- FETCH WITH DIAGNOSTICS ----
      - name: Fetch CableTV feed
        env:
          FEED_URL: https://rss.app/feeds/IPTSK5jPaETkAX2v.xml
        run: |
          set -euxo pipefail
          echo "Fetching: $FEED_URL"
          curl -sS -D headers.txt -o smartnews-source.xml \
            -A "Mozilla/5.0 (GitHubActions; +https://github.com/actions)" \
            -H "Accept: application/rss+xml, application/xml;q=0.9, text/xml;q=0.8, */*;q=0.1" \
            -L --max-redirs 5 --retry 3 --retry-delay 5 "$FEED_URL"
          echo "---- Response headers ----"; cat headers.txt || true
          echo "---- File size (bytes) ----"; wc -c smartnews-source.xml || true
          echo "---- First 200 bytes ----"; head -c 200 smartnews-source.xml | sed 's/</\&lt;/g' || true
          test -s smartnews-source.xml

      # ---- VALIDATE IT'S REAL XML ----
      - name: Validate XML (fail if HTML or not well-formed)
        run: |
          set -euxo pipefail
          if head -c 400 smartnews-source.xml | grep -qiE '<!doctype html|<html'; then
            echo "::error ::Downloaded content looks like HTML, not RSS XML. Check FEED_URL."; exit 2
          fi
          xmllint --noout smartnews-source.xml

      # Ensure index and .nojekyll exist (served by Pages)
      - name: Ensure index & .nojekyll
        run: |
          if [ ! -f index.html ]; then
            cat > index.html <<'HTML'
          <!doctype html>
          <html><head><meta charset="utf-8"><title>CableTV SmartNews Feed</title></head>
          <body><h1>CableTV SmartNews Feed</h1>
          <p><a href="smartnews-source.xml">Open smartnews-source.xml</a></p></body></html>
          HTML
          fi
          touch .nojekyll
          ls -la

      # Configure Pages (no enablement flag)
      - name: Configure Pages
        uses: actions/configure-pages@v5

      # Upload & deploy repo root (includes XML + index + .nojekyll)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."
      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
